version: "3"

services:
  api:     
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./api/:/api
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=api.localhost
    command: ["pipenv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  celery: # Celery service for background tasks with hot-reload using watchdog
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./api/:/api
    environment:
      - VIRTUAL_HOST=celery.localhost
      - CELERY_BROKER_URL=redis://redis:6379/0 # Use the Redis service as the broker
    command: ["pipenv", "run", "python", "api_job_queues.py"]
    depends_on:
      - api
      - redis

  redis: # Redis service to act as the broker for Celery
    image: "redis:latest"
    ports:
      - "6379:6379"
